### PR TITLE
build against old Numpy, rerender

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by marscher** [comment]
On 21.01.2018 15:47, Isuru Fernando wrote:
> @conda-forge-admin, please rerender
> 

I just rerendered myself with 2.4.5

**Comment by marscher** [comment]
first ci run (failed because of syntax error in recipe) picked up that it should only build one configuration. I don't know why now it tries to build against all numpy versions...

**Comment by marscher** [comment]
I see... doh :) thanks for taking care of this @isuruf

**Pull request merged**
